=== openbig/odoo-banking-germany/hibi/workspace2/jameica.webadmin/build/jameica-webtools-1.0.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!--
  $Revision: 1.1 $
  $Date: 2010/10/27 14:32:18 $
  $Author: willuhn $
 
  Copyright (c) by willuhn software & services
  All rights reserved

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

-->

<xsd:schema xml:lang="DE" elementFormDefault="qualified"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.willuhn.de/schema/jameica-webtools"
  xmlns:tns="http://www.willuhn.de/schema/jameica-webtools">

  <xsd:annotation>
     <xsd:documentation>
       XML-Spezifikation des XML-Formats fuer die "webtools.xml" von Webanwendungen, die
       das jameica.webtools Framework nutzen.
     </xsd:documentation>
  </xsd:annotation>

  <!-- Root-Element //-->
  <xsd:element name="webtools" type="tns:webtoolsType" />

  <!-- Element "webtools" //-->
  <xsd:complexType name="webtoolsType">
    <xsd:annotation>
      <xsd:documentation>Root-Element einer webtools.xml</xsd:documentation>
    </xsd:annotation>
    <xsd:choice>
      <xsd:element name="beans" type="tns:beansType" minOccurs="0" maxOccurs="1" />
      <xsd:element name="pages" type="tns:pagesType" minOccurs="1" maxOccurs="1" />
    </xsd:choice>
  </xsd:complexType>


  <!-- Element "pages" //-->
  <xsd:complexType name="pagesType">
    <xsd:annotation>
      <xsd:documentation>Container-Element fuer die einzelnen Seiten</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:annotation>
        <xsd:documentation>Enthält die Liste der definierten Pages</xsd:documentation>
      </xsd:annotation>
      <xsd:element name="page" type="tns:pageType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>


  <!-- Element "page" //-->
  <xsd:complexType name="pageType">
    <xsd:annotation>
      <xsd:documentation>Definition einer einzelnen Page.</xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="pattern" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          Regulärer Ausdruck, auf den der aktuelle PathInfo passen muss, 
          damit diese Page ausgewählt wird.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="template" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          Dateiname des zu verwendenden Velocity-Templates. Die Template-Datei
          muss sich im Verzeichnis lib/velocity des Plugins befinden.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="action" type="xsd:string" use="optional">
      <xsd:annotation>
        <xsd:documentation>
          Optionale Default-Action, die ausgefuehrt wird, wenn im HTTP-Request
          keine angegeben ist.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="controller" type="xsd:string" use="optional">
      <xsd:annotation>
        <xsd:documentation>
          Name der Java-Klasse des zugehoerigen Controllers, falls einer
          verwendet werden soll. Ein Controller ist eine ganz normale
          Bean mit parameterlosem Konstruktor.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

  <!-- Element "beans" //-->
  <xsd:complexType name="beansType">
    <xsd:annotation>
      <xsd:documentation>Container-Element fuer allgemeine Beans</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:annotation>
        <xsd:documentation>Enthält die Liste der definierten Beans</xsd:documentation>
      </xsd:annotation>
      <xsd:element name="bean" type="tns:beanType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <!-- Element "bean" //-->
  <xsd:complexType name="beanType">
    <xsd:annotation>
      <xsd:documentation>Definition einer einzelnen Bean.</xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="name" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          Alias-Name, unter der die Bean verfuegbar sein soll.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
    <xsd:attribute name="class" type="xsd:string" use="required">
      <xsd:annotation>
        <xsd:documentation>
          Name der Java-Klasse der Bean.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
  </xsd:complexType>

</xsd:schema>

=== openbig/odoo-banking-germany/hibi/workspace2/hibiscus.server/webapps/hibiscus/WEB-INF/webtools.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<webtools xmlns:wt="http://www.willuhn.de/schema/jameica-webtools"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.willuhn.de/schema/jameica-webtools http://www.willuhn.de/schema/jameica-webtools-1.0.xsd ">

  <!-- Global verfuegbare Beans -->
  <beans>
    <bean name="meta"      class="de.willuhn.jameica.hbci.payment.web.beans.Meta" />
    <bean name="message"   class="de.willuhn.jameica.hbci.payment.web.beans.Message" />
    <bean name="protokoll" class="de.willuhn.jameica.hbci.payment.web.beans.Protokoll" />
    <bean name="jobs"      class="de.willuhn.jameica.hbci.payment.web.beans.Jobs" />
    <bean name="format"    class="de.willuhn.jameica.hbci.payment.web.beans.Format" />
    <bean name="chart"     class="de.willuhn.jameica.hbci.payment.web.beans.Chart" />
  </beans>

  <!-- Die konkreten Pages -->
  <pages>
    <page pattern="^/settings.html"         template="settings.vm"         controller="de.willuhn.jameica.hbci.payment.web.beans.Settings"/>
    <page pattern="^/importieren.html"      template="importieren.vm"      controller="de.willuhn.jameica.hbci.payment.web.beans.Importieren" action="store"/>
    <page pattern="^/passports.html"        template="passports.vm"        controller="de.willuhn.jameica.hbci.payment.web.beans.Passports" />
    <page pattern="^/passports.pintan.html" template="passports.pintan.vm" controller="de.willuhn.jameica.hbci.payment.web.beans.PassportsPinTan" action="load" />
    <page pattern="^/passports.rdh.html"    template="passports.rdh.vm"    controller="de.willuhn.jameica.hbci.payment.web.beans.PassportsRdh" action="store" />
    <page pattern="^/passports.ddv.html"    template="passports.ddv.vm"    controller="de.willuhn.jameica.hbci.payment.web.beans.PassportsDdv" action="load" />
    <page pattern="^/accounts.html"         template="accounts.vm"         controller="de.willuhn.jameica.hbci.payment.web.beans.Accounts" />
    <page pattern="^/account.html"          template="account.vm"          controller="de.willuhn.jameica.hbci.payment.web.beans.Account" action="load" />

    <page pattern="^/log.html"              template="log.vm" />
    
    <!-- Default-Seite -->
    <page pattern=".*"                      template="index.vm"            controller="de.willuhn.jameica.hbci.payment.web.beans.Welcome" />
  </pages>
  
  
</webtools>

=== openbig/odoo-banking-germany/hibi/workspace2/jameica.webadmin/webapps/webadmin/WEB-INF/webtools.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<webtools xmlns:wt="http://www.willuhn.de/schema/jameica-webtools"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.willuhn.de/schema/jameica-webtools http://www.willuhn.de/schema/jameica-webtools-1.0.xsd ">

  <!-- Global verfuegbare Beans -->
  <beans>
    <bean name="application" class="de.willuhn.jameica.webadmin.rest.Application" />
    <bean name="certificate" class="de.willuhn.jameica.webadmin.rest.Certificate" />
    <bean name="log"         class="de.willuhn.jameica.webadmin.rest.Log" />
    <bean name="plugin"      class="de.willuhn.jameica.webadmin.rest.Plugin" />
    <bean name="server"      class="de.willuhn.jameica.webadmin.rest.Server" />
    <bean name="service"     class="de.willuhn.jameica.webadmin.rest.Service" />
    <bean name="restdoc"     class="de.willuhn.jameica.webadmin.rest.RestDoc" />
  </beans>

  <!-- Die konkreten Pages -->
  <pages>
    <page pattern="^/rest.html"   template="rest.vm" />
    <page pattern="^/cert.html"   template="cert.vm"   controller="de.willuhn.jameica.webadmin.rest.Certificate" action="upload" />
    <page pattern="^/plugin.html" template="plugin.vm" controller="de.willuhn.jameica.webadmin.rest.Plugin" />
    
    <!-- Default-Seite -->
    <page pattern=".*"            template="index.vm" />
  </pages>
  
  
</webtools>
